/**
 * BentoGrid - Consolidated physics grid scaffold.
 *
 * Phase 1 exposes the merged type and constant surface while the component
 * implementation is ported from InfiniteGrid and UnifiedGrid in later phases.
 */

export type {
  BaseCardData,
  BentoGridProps,
  Bounds,
  Camera,
  CanvasState,
  CardData,
  CardLayout,
  CardPoolState,
  CardPosition,
  CardQueueState,
  CardSize,
  CardType,
  ExclusionZone,
  GameCardData,
  GridLayoutConfig,
  GridNavigationBindings,
  GridTheme,
  LayoutTransition,
  NavigationState,
  PhysicsCard,
  PhysicsConfig,
  PhysicsPosition,
  Point,
  PooledCard,
  Position,
  ProjectCardData,
  ProjectCardProps,
  QueuedCard,
  RenderCard,
  SearchCardEdge,
  SearchCardProps,
  SearchCardState,
  Size,
  SpawnEdge,
  StickyEdge,
  ThemeConfig,
  TransitionPhase,
  UseBentoLayoutReturn,
  UseCameraReturn,
  UseCardNavigationReturn,
  UseCardPoolReturn,
  UseCardQueueReturn,
  UsePhysicsWorldReturn,
  UseSpawnManagerReturn,
  UseViewportReturn,
  Velocity,
  ViewportBounds,
} from './BentoGrid.types';

export {
  ANIMATION,
  CAMERA,
  CARD_POOL,
  CARD_SIZES,
  DEFAULT_CAMERA,
  GRID,
  INTERACTION,
  KEYBOARD,
  MOBILE,
  PERFORMANCE,
  PHYSICS,
  PHYSICS_MOBILE,
  QUEUE,
  SEARCH_CARD,
  SPATIAL_HASH_CELL_SIZE,
  STICKY,
  STORAGE_KEY,
  THEME_PLAYFUL,
  THEME_PREMIUM,
  THEMES,
  VIEWPORT_BUFFER,
  Z_INDEX,
  getCardDimensions,
} from './BentoGrid.constants';
