import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Pixelify_Sans,
  VT323,
  DotGothic16,
  Press_Start_2P,
  Workbench,
  Silkscreen,
  Major_Mono_Display,
  Iceland,
  Russo_One,
  Squada_One,
  Orbitron,
} from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { siteConfig } from '@/lib/site-config';
import { ThemeProvider } from '@/lib/theme-context';
import { PageTransition } from '@/components/ui/PageTransition';
import { ToastProvider } from '@/components/ui/Toast';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Pixelated display font for the bentOS wordmark on the boot screen.
const pixelifySans = Pixelify_Sans({
  variable: '--font-pixel',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

// Bitmap CRT terminal font for diegetic boot chrome (corner status, footer).
const vt323 = VT323({
  variable: '--font-crt',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// Square-dot pixel display font alternative for the boot wordmark.
const dotGothic = DotGothic16({
  variable: '--font-dot',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// 8-bit arcade pixel font alternative for the boot wordmark.
const pressStart = Press_Start_2P({
  variable: '--font-arcade',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// Variable-axis pixel font — modern, sized via a single weight axis.
const workbench = Workbench({
  variable: '--font-workbench',
  subsets: ['latin'],
  display: 'swap',
});

// Small/medium pixel font — chunky square bitmap style.
const silkscreen = Silkscreen({
  variable: '--font-silkscreen',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

// Geometric mono display — outlined glyphs, alternative pixel-adjacent vibe.
const majorMono = Major_Mono_Display({
  variable: '--font-mono-display',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// Iceland — geometric square mono with a CGA/Video-style character.
const iceland = Iceland({
  variable: '--font-iceland',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// Russo One — chunky square display, single weight.
const russoOne = Russo_One({
  variable: '--font-russo',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// Squada One — chunky square display, single weight.
const squadaOne = Squada_One({
  variable: '--font-squada',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

// Orbitron — geometric square sans used for the bentOS boot wordmark (700/800).
const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
  weight: ['700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  // Basic metadata
  title: {
    default: `bentOS — ${siteConfig.name}`,
    template: `%s | bentOS`,
  },
  description: `bentOS — ${siteConfig.description}`,
  keywords: [...siteConfig.keywords],
  authors: [{ name: siteConfig.name }],
  creator: siteConfig.name,

  // Open Graph (images auto-generated by opengraph-image.tsx)
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.url,
    title: `bentOS — ${siteConfig.name}`,
    description: `bentOS — ${siteConfig.description}`,
    siteName: 'bentOS',
  },

  // Twitter Card (images auto-generated by opengraph-image.tsx)
  twitter: {
    card: 'summary_large_image',
    title: `bentOS — ${siteConfig.name}`,
    description: `bentOS — ${siteConfig.description}`,
  },

  // Favicons and app icons
  icons: {
    icon: [{ url: '/favicon.ico', sizes: 'any' }],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }],
  },

  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  // Metadata base for resolving relative URLs
  metadataBase: new URL(siteConfig.url),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        {/* Prevent flash of wrong theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const stored = localStorage.getItem('portfolio-theme');
                  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  const theme = stored || (prefersDark ? 'dark' : 'light');
                  document.documentElement.classList.add(theme);
                  document.documentElement.style.colorScheme = theme;
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pixelifySans.variable} ${vt323.variable} ${dotGothic.variable} ${pressStart.variable} ${workbench.variable} ${silkscreen.variable} ${majorMono.variable} ${iceland.variable} ${russoOne.variable} ${squadaOne.variable} ${orbitron.variable} antialiased`}
      >
        <a href="#main-content" className="skip-to-content">
          Skip to main content
        </a>
        <ThemeProvider>
          <ToastProvider>
            <PageTransition>{children}</PageTransition>
          </ToastProvider>
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
