import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// Plain ESM helper, shared with the sync CLIs.
import { writeGeneratedBundle } from '../../../scripts/generated-bundle.mjs';

/**
 * `src/content/*.generated.json` are committed and regenerated by every
 * `npm run dev` / `npm run build`. Stamping a fresh `generatedAt` on each run
 * left the working tree permanently dirty: it blocks branch switches, and the
 * Studio's commit flow (which stages `src/content`) picked up timestamp-only
 * diffs nobody asked for.
 */

let dir: string;
let file: string;

beforeAll(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), 'generated-bundle-'));
  file = path.join(dir, 'bundle.generated.json');
});

afterAll(async () => {
  await fs.rm(dir, { recursive: true, force: true });
});

async function read() {
  return JSON.parse(await fs.readFile(file, 'utf8')) as { generatedAt: string; items: string[] };
}

describe('writeGeneratedBundle', () => {
  it('keeps the previous timestamp when the content is unchanged', async () => {
    await writeGeneratedBundle(file, { items: ['a', 'b'] });
    const first = await read();

    await new Promise((resolve) => setTimeout(resolve, 5));
    await writeGeneratedBundle(file, { items: ['a', 'b'] });
    const second = await read();

    expect(second.generatedAt).toBe(first.generatedAt);
  });

  it('bumps the timestamp when the content actually changes', async () => {
    await writeGeneratedBundle(file, { items: ['a', 'b'] });
    const before = await read();

    await new Promise((resolve) => setTimeout(resolve, 5));
    await writeGeneratedBundle(file, { items: ['a', 'b', 'c'] });
    const after = await read();

    expect(after.generatedAt).not.toBe(before.generatedAt);
    expect(after.items).toEqual(['a', 'b', 'c']);
  });

  it('writes generatedAt first so the committed key order is stable', async () => {
    await writeGeneratedBundle(file, { items: ['x'] });
    const raw = await fs.readFile(file, 'utf8');
    expect(Object.keys(JSON.parse(raw))[0]).toBe('generatedAt');
    expect(raw.endsWith('\n')).toBe(true);
  });

  it('handles a missing target file', async () => {
    const fresh = path.join(dir, 'new.generated.json');
    await writeGeneratedBundle(fresh, { items: [] });
    expect(JSON.parse(await fs.readFile(fresh, 'utf8')).generatedAt).toEqual(expect.any(String));
  });
});
